//USERS HTTP TEST
###
GET http://localhost:5253/api/user

###
GET http://localhost:5253/api/user/eda759fe-035d-4d44-b10e-67800ced4ecd

###
GET http://localhost:5253/api/user/user_name/kurobattv


###
POST  http://localhost:5253/api/user
Content-Type: application/json

{
    "Username": "nicky142.m",
    "FirstName": "Nirisy",
    "LastName": "Martinez",
    "Email": "nirisy142@gmail.com",
    "PhoneNumber": "9504-4932",
    "Password": "Niriy2021!"
}

###
POST  http://localhost:5253/api/user
Content-Type: application/json

{
    "Username": "kurobattv",
    "FirstName": "Alessandro",
    "LastName": "Ayestas",
    "Email": "aleayestas@gmail.com",
    "PhoneNumber": "9236-4565",
    "Password": "Asta2021!"
}
###
###
POST  http://localhost:5253/api/user
Content-Type: application/json

{
    "Username": "mariajones",
    "FirstName": "Maria",
    "LastName": "Jones",
    "Email": "maria.jones@example.com",
    "PhoneNumber": "9123-4567",
    "Password": "Maria2021!"
}
###
POST  http://localhost:5253/api/user
Content-Type: application/json

{
    "Username": "johnsmith",
    "FirstName": "John",
    "LastName": "Smith",
    "Email": "john.smith@example.com",
    "PhoneNumber": "9345-6789",
    "Password": "John2021!"
}
###
POST  http://localhost:5253/api/user
Content-Type: application/json

{
    "Username": "emilyclark",
    "FirstName": "Emily",
    "LastName": "Clark",
    "Email": "emily.clark@example.com",
    "PhoneNumber": "9456-7890",
    "Password": "Emily2021!"
}
###
POST  http://localhost:5253/api/user
Content-Type: application/json

{
    "Username": "davidharris",
    "FirstName": "David",
    "LastName": "Harris",
    "Email": "david.harris@example.com",
    "PhoneNumber": "9567-8901",
    "Password": "David2021!"
}
###
POST  http://localhost:5253/api/user
Content-Type: application/json

{
    "Username": "sarajones",
    "FirstName": "Sara",
    "LastName": "Jones",
    "Email": "sara.jones@example.com",
    "PhoneNumber": "9678-9012",
    "Password": "Sara2021!"
}
###
POST  http://localhost:5253/api/user
Content-Type: application/json

{
    "Username": "michaelbrown",
    "FirstName": "Michael",
    "LastName": "Brown",
    "Email": "michael.brown@example.com",
    "PhoneNumber": "9789-0123",
    "Password": "Michael2021!"
}
###
POST  http://localhost:5253/api/user
Content-Type: application/json

{
    "Username": "lindawilliams",
    "FirstName": "Linda",
    "LastName": "Williams",
    "Email": "linda.williams@example.com",
    "PhoneNumber": "9890-1234",
    "Password": "Linda2021!"
}
###
POST  http://localhost:5253/api/user
Content-Type: application/json

{
    "Username": "jameslee",
    "FirstName": "James",
    "LastName": "Lee",
    "Email": "james.lee@example.com",
    "PhoneNumber": "9901-2345",
    "Password": "James2021!"
}
###
POST  http://localhost:5253/api/user
Content-Type: application/json

{
    "Username": "annasmith",
    "FirstName": "Anna",
    "LastName": "Smith",
    "Email": "anna.smith@example.com",
    "PhoneNumber": "9012-3456",
    "Password": "Anna2021!"
}


###
PUT http://localhost:5253/api/user/1459a511-7390-4112-b4e9-279285aba59d
Content-Type: application/json

{
    "Username": "KurobaTTV",
    "FirstName": "Alessandro",
    "LastName": "Ayestas",
    "Email": "blackuroba21@gmail.com",
    "PhoneNumber": "9236-4565"
}

###
DELETE http://localhost:5253/api/user/69622192-ef1b-49b3-9047-19dc9957105d

###
DELETE http://localhost:5253/api/user/user_name/kurobattv


###
POST http://localhost:5253/api/auth/login
Content-Type: application/json

{
    "UserName": "kurobattv",
    "Password": "Asta2021!"
}

### 
Post http://localhost:5253/api/auth/login_params/kurobattv/Asta2021!
