###
GET http://localhost:5280/api/booking

###
GET http://localhost:5280/api/booking/3

###
GET http://localhost:5280/api/booking/user_name/kurobattv

###
GET http://localhost:5280/api/booking/event_id/1

###
GET http://localhost:5280/api/booking/event_name/Coachella


###
POST http://localhost:5280/api/booking
Content-Type: application/json

{
    "Username": "mariajones",
    "EventId": 3,
    "Amount": 10
}
###
POST http://localhost:5280/api/booking
Content-Type: application/json

{
    "Username": "mariajones",
    "EventId": 2,
    "Amount": 150
}
###
POST http://localhost:5280/api/booking
Content-Type: application/json

{
    "Username": "johnsmith",
    "EventId": 6,
    "Amount": 20
}
###
POST http://localhost:5280/api/booking
Content-Type: application/json

{
    "Username": "emilyclark",
    "EventId": 6,
    "Amount": 180
}
###
POST http://localhost:5280/api/booking
Content-Type: application/json

{
    "Username": "davidharris",
    "EventId": 5,
    "Amount": 220
}
###
POST http://localhost:5280/api/booking
Content-Type: application/json

{
    "Username": "sarajones",
    "EventId": 6,
    "Amount": 160
}
###
POST http://localhost:5280/api/booking
Content-Type: application/json

{
    "Username": "michaelbrown",
    "EventId": 2,
    "Amount": 130
}
###
POST http://localhost:5280/api/booking
Content-Type: application/json

{
    "Username": "lindawilliams",
    "EventId": 3,
    "Amount": 20
}
###
POST http://localhost:5280/api/booking
Content-Type: application/json

{
    "Username": "jameslee",
    "EventId": 3,
    "Amount": 20
}


###
POST http://localhost:5280/api/booking/create_req_name/kurobattv/Coachella/10


###
Delete http://localhost:5280/api/booking/user_event/henryadams/13

### 
DELETE http://localhost:5280/api/booking/8

###
DELETE http://localhost:5280/api/booking/user_eventname/kurobattv/SXSW