###
GET http://localhost:5280/bookings

###
GET http://localhost:5280/bookings/3

###
GET http://localhost:5280/bookings/user_name/kurobattv

###
GET http://localhost:5280/bookings/event_id/1

###
POST http://localhost:5280/bookings
Content-Type: application/json

{
    "Username": "kurobattv",
    "EventId": 1,
    "Amount": 100
}
###
POST http://localhost:5280/bookings
Content-Type: application/json

{
    "Username": "mariajones",
    "EventId": 2,
    "Amount": 150
}
###
POST http://localhost:5280/bookings
Content-Type: application/json

{
    "Username": "johnsmith",
    "EventId": 3,
    "Amount": 200
}
###
POST http://localhost:5280/bookings
Content-Type: application/json

{
    "Username": "emilyclark",
    "EventId": 4,
    "Amount": 180
}
###
POST http://localhost:5280/bookings
Content-Type: application/json

{
    "Username": "davidharris",
    "EventId": 5,
    "Amount": 220
}
###
POST http://localhost:5280/bookings
Content-Type: application/json

{
    "Username": "sarajones",
    "EventId": 6,
    "Amount": 160
}
###
POST http://localhost:5280/bookings
Content-Type: application/json

{
    "Username": "michaelbrown",
    "EventId": 2,
    "Amount": 130
}
###
POST http://localhost:5280/bookings
Content-Type: application/json

{
    "Username": "lindawilliams",
    "EventId": 4,
    "Amount": 140
}
###
POST http://localhost:5280/bookings
Content-Type: application/json

{
    "Username": "jameslee",
    "EventId": 1,
    "Amount": 170
}



###
Delete http://localhost:5280/bookings/user_event/henryadams/13

### 
DELETE http://localhost:5280/bookings/8